bootstrapDns:
  - upstream: 127.0.0.11

upstreams:
  groups:
    default:
      - unbound

customDNS:
  customTTL: 5m
  mapping:
    ash.${domain}: ${ash_ip}
    birds.${domain}: ${hickory_ip}
    bookmarks.${domain}: ${hickory_ip}
    cherry.${domain}: ${cherry_ip}
    db.${domain}: ${ash_ip}
    docs.${domain}: ${cherry_ip}
    git.${domain}: ${hickory_ip}
    glance.${domain}: ${hickory_ip}
    hickory.${domain}: ${hickory_ip}
    home.${domain}: ${maple_ip}
    logs.${domain}: ${hickory_ip}
    maple.${domain}: ${maple_ip}
    pdf.${domain}: ${hickory_ip}
    prometheus.${domain}: ${ash_ip}
    rss.${domain}: ${hickory_ip}
    waka.${domain}: ${hickory_ip}
    zwave.${domain}: ${maple_ip}

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

ports:
  dns: 53
  http: 4000
